auth_enabled: false
server:
  http_listen_port: 3100
common:
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
  path_prefix: /loki
storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache
    cache_ttl: 24h
schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
limits_config:
  allow_structured_metadata: true
compactor:
  working_directory: /loki/compactor